### PR TITLE
Added file for 3d pose estimation

### PR DESCRIPTION
**Pull request by mahipalimkar**
This PR introduces 3D Pose Estimation functionality to the repository, allowing users to estimate human body poses in three-dimensional space from input data such as 2D pose coordinates or video streams.
This code performs real-time 3D pose estimation using a webcam feed, Mediapipe's Pose model, and sends the detected 3D landmarks to a Unity application via UDP.

### CODE REVIEW

**Comment by mahipalimkar** [comment]
Hello, made a pr for 3d pose estimation.

**Comment by UppuluriKalyani** [comment]
@mahipalimkar add readme file with proper description with attachment of results 
And also show results here(screenshots or screen recording)

**Comment by mahipalimkar** [comment]
@UppuluriKalyani Did the changes. Please check

**Comment by mahipalimkar** [comment]
@UppuluriKalyani 
image
also added a result video

**Pull request merged**
