### PR TITLE
Transfer Learning for Accident Classifier #41 but structuring the files remains 

### PR DESCRIPTION
**Pull request by Pseudophoenix**
I have trained the yolov5 to 80 epochs and will be going for further updates ahead.
Screenshot from 2024-10-03 19-48-46

Currently Hosted at: https://52dc-35-237-253-65.ngrok-free.app/

Returns "Severe" for an image of severe accident car image else "moderate"

### CODE REVIEW

**Comment by UppuluriKalyani** [comment]
@Pseudophoenix mention the issue you solved

**Comment by Pseudophoenix** [comment]
Feature request Accident Classifier #41 
I have also attached the dataset that I used to train. Shall I remove it and then try again?

**Comment by Pseudophoenix** [comment]
> @Pseudophoenix yeah just add the data set link in readme file..and keep only implementation of the project,clear description of project in readme file and show me the results

ok...will do

**Comment by Pseudophoenix** [comment]
I will also be adding some more features to this same project in future. Like Web Page Front-End I hope we are allowed to do so.

**Comment by UppuluriKalyani** [comment]
> I will also be adding some more features to this same project in future. Like Web Page Front-End I hope we are allowed to do so.

Yes you can

**Comment by UppuluriKalyani** [comment]
> > I will also be adding some more features to this same project in future. Like Web Page Front-End I hope we are allowed to do so.
> 
> Yes you can,you already implemented it isn't it so add those files too(that implementation)

**Pull request closed without merging**
