### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Panchadip-128**
Issue #237 Flight Fare Prediction Model

Issue Link: https://github.com/UppuluriKalyani/ML-Nexus/issues/237

# Related Issues or bug
  - Info about Issue or bug

Fixes: #237 

# Proposed Changes
 - This project focuses on predicting flight prices using machine learning techniques, specifically employing the RandomForestRegressor from scikit-learn. The dataset used contains comprehensive flight details sourced from Kaggle, including airline information, source and destination cities, flight duration, total stops, and ticket prices.
 
# Additional Info
  - Anything related Issues 
  
# Screenshots

ffp4
ffp3
ffp2
ffp1

### CODE REVIEW

**Comment by Panchadip-128** [comment]
I have added the required file containing ML Model for Flight Fare Prediction

**Review by UppuluriKalyani — CHANGES_REQUESTED** [review]
@Panchadip-128 see you were done some changes in movies recommendations folder and also keep your implementation under 
Neural networks folder

**Comment by Panchadip-128** [comment]
> @Panchadip-128 see you were done some changes in movies recommendations folder and also keep your implementation under Neural networks folder

Mam, I have made the requested changes, By mistake it was from other sub repo which got uploaded to this issue. Inconveniences regretted

**Comment by UppuluriKalyani** [comment]
> > @Panchadip-128 see you were done some changes in movies recommendations folder and also keep your implementation under Neural networks folder
> 
> Mam, I have made the requested changes, By mistake it was from other sub repo which got uploaded to this issue. Inconveniences regretted

Why are you keep changing existing files just put your implementation under prediction models why are you trying to do changes in readme file ?

**Pull request closed without merging**
