### PR TITLE
Added Face Recognition System project

### PR DESCRIPTION
**Pull request by anirudh-248**
I have added the requirements file.

Create a virtual environment and install the requirements.

DISCLAIMER: Before installing the requirements, install dlib separately using `pip install "path_to_dlib_file\dlib-19.24.99-cp312-cp312-win_amd64.whl"`

### CODE REVIEW

**Comment by anirudh-248** [comment]
I have also added an attendance feature along with the face recognition system

**Comment by SaiNivedh26** [comment]
@anirudh-248 Make sure to add documentation as README file. 
Using streamlit, make a simple UI, where user can upload the image then it can detect the known face and mark attendance accordingly. Once this is done, it'll be merged with the main branch

**Comment by anirudh-248** [comment]
added the requested changes in the face_rec.py file, which contains the streamlit UI and recognizes faces from a provided image. please let me know if anything else is needed.

**Comment by UppuluriKalyani** [comment]
@SaiNivedh26 Please review this

**Review by SaiNivedh26 — APPROVED** [review]

**Pull request merged**
