### PR TITLE
Eye Desease Detection Added In Prediction Models

### PR DESCRIPTION
**Pull request by deepanshubaghel**
Fixes: #252 

  
{8AD3C900-D0E4-47B1-8120-F27CBBE0FFCC}

### CNN on Category

{A997732C-96B0-45F5-AE26-68856B6AAD6F}

image

### MobileNetV2 on Type

{168BFC93-C6B0-42EF-9735-C3641E2D88FC}

image

### CODE REVIEW

**Comment by UppuluriKalyani** [comment]
@deepanshubaghel 1200+ files🥲.. just remove that argumened images folder or keep 5 examples.

**Comment by deepanshubaghel** [comment]
> @deepanshubaghel 1200+ files🥲.. just remove that argumened images folder or keep 5 examples.

@UppuluriKalyani please review it i have deleted the augmented images and few samples added in dataset dir

**Comment by deepanshubaghel** [comment]
@UppuluriKalyani  please dont forget to assign level

**Review by UppuluriKalyani — APPROVED** [review]

**Comment by deepanshubaghel** [comment]
@UppuluriKalyani  Level 1 🥲

**Pull request merged**
