### PR TITLE
Text-to-Speech model using Transformers

### PR DESCRIPTION
**Pull request by PrasannaKasar**
<h2>Solved issue #578 </h2>
<h2>Problem statement</h2>
<p>Current TTS solutions frequently produce robotic and monotonous speech that fails to convey emotional nuance and context, resulting in reduced comprehension and engagement for users. Additionally, many systems struggle with the accurate pronunciation of complex words, proper names, and domain-specific terminology. </p>
<h2>Objectives</h2>
<p><b>Naturalness and Expressiveness:</b> Develop a TTS system that generates speech with human-like intonation, rhythm, and emotional expression to enhance user engagement.
<br>
<b>Contextual Understanding:</b> Implement algorithms that allow the system to accurately interpret context, improving pronunciation and intonation based on the text's meaning.</p>
<h2>Implementation</h2>
<p>In this implementation, we will follow a non-end-to-end approach, comprising two main components: the frontend and the backend. The frontend consists of a Transformer model that takes text as input and predicts the mel spectrogram. This predicted mel spectrogram is then utilized by the backend to construct the audio waveform, resulting in high-quality, human-like speech. This modular approach allows for greater flexibility and optimization in both the acoustic modeling and audio synthesis stages.</p>

### CODE REVIEW

**Comment by UppuluriKalyani** [comment]
@PrasannaKasar mention the issue you sloved

**Comment by PrasannaKasar** [comment]
@UppuluriKalyani plz check once
I have mentioned the issue

**Comment by UppuluriKalyani** [comment]
> @UppuluriKalyani plz check once I have mentioned the issue

It's already existed why did you done it and why are you raising issue after PR.
I'm closing this one please try to raise different ideas and wait until it assign to you then make PR.

**Comment by PrasannaKasar** [comment]
@UppuluriKalyani very sorry for this pr
I sent the pr before raising an issue
The solution to TTS already exists but it uses an end to end approach and my project used non end to end approach
From now on will look for already existing projects and issues beforehand

**Review by UppuluriKalyani — APPROVED** [review]

**Comment by UppuluriKalyani** [comment]
> @UppuluriKalyani very sorry for this pr I sent the pr before raising an issue The solution to TTS already exists but it uses an end to end approach and my project used non end to end approach From now on will look for already existing projects and issues beforehand

It's ok no problem from next time onwards don't do this.

**Pull request merged**
