### PR TITLE
Hand Game Controller using OpenCV

### PR DESCRIPTION
**Pull request by aviralgarg05**
Hand Game Controller using OpenCV
Solving Issue #58 
I am a GSSOC'24 Extended and Hacktoberfest Contributor

### CODE REVIEW

**Comment by UppuluriKalyani** [comment]
@aviralgarg05 can you share the screenshots of results or screen recording

**Comment by aviralgarg05** [comment]
Should I upload them in the folder or just present them here?

**Comment by UppuluriKalyani** [comment]
@aviralgarg05 first show here

**Comment by aviralgarg05** [comment]
Screenshot 2024-10-03 171333
Screenshot 2024-10-03 171318
Screenshot 2024-10-03 171255
Screenshot 2024-10-03 171234

**Comment by aviralgarg05** [comment]
For different hand positions different key bindings are present, they can be printed in the terminal as well as work in games too

**Comment by UppuluriKalyani** [comment]
@aviralgarg05 Please modify the project to capture hand gestures via the webcam instead of using raw input, so I can clearly see how the hand gestures are detected

**Review by UppuluriKalyani — CHANGES_REQUESTED** [review]
@aviralgarg05 Please modify the project to capture hand gestures via the webcam instead of using raw input, so I can clearly see how the hand gestures are detected

**Comment by aviralgarg05** [comment]
Screenshot 2024-10-03 183644
Screenshot 2024-10-03 183619
Screenshot 2024-10-03 183129
Screenshot 2024-10-03 183106



I guess now it is clear. If yes then I will commit the changes.

**Comment by UppuluriKalyani** [comment]
@aviralgarg05 yes go ahead!

**Comment by UppuluriKalyani** [comment]
@aviralgarg05 can you please add these results attachments in readme file then will merge it

**Review by UppuluriKalyani — APPROVED** [review]

**Comment by UppuluriKalyani** [comment]
@aviralgarg05 good,and please star the repo if you find it helpful

**Pull request merged**
