### PR TITLE
Added New project Plant Leaf Detection

### LINKED ISSUE #33: New Project "Plant disease detection" addition under neural network/
We need to integrate a new project focused on plant disease detection, which is currently missing from the repository. This would help in detecting and diagnosing plant diseases using image processing or machine learning techniques.

### PR DESCRIPTION
**Pull request by Mayank202004**
**Added New project Plant Leaf Detection**

- Added Basic structure
- Added readme
- Added Requirments
- Added Potato image classification for disease.

Fixes #33

### CODE REVIEW

**Comment by UppuluriKalyani** [comment]
@Mayank202004 can you please share results  and add this in neural networks folder

**Comment by Mayank202004** [comment]
@UppuluriKalyani I will be adding ipynb files for more plants' disease detection as I progress. Currently I will just add results obtained for potato model which is added.

**Comment by UppuluriKalyani** [comment]
@Mayank202004  After finishing all these things add results with clear description, after i will merge it

**Comment by Mayank202004** [comment]
@UppuluriKalyani can you check now if it is in correct format?

**Review by UppuluriKalyani — APPROVED** [review]

**Comment by UppuluriKalyani** [comment]
@Mayank202004 Approved🎉

**Pull request merged**
