### PR TITLE
Iris Flower Classification

### PR DESCRIPTION
**Pull request by aviralgarg05**
Iris Flower Classification using Machine Learning.
Solving Issue #79 
GSSOC'24 Extended and Hacktoberfest

### CODE REVIEW

**Comment by Neilblaze** [comment]
@aviralgarg05 LGTM! One suggestion that I'd provide is to add screenshots (preferably.gif's) with the README file. Once done, I'll approve the PR. Thanks for contributing! ✨

**Comment by aviralgarg05** [comment]
There aren't as such Images or gifs, there are only graphs. Rest the accuracy is calculated on testing data(split from training dataset). 
If you want I can put all graph images, confusion matrices etc.

**Comment by Neilblaze** [comment]
I referred to the graph images, and to your point, sure you can add more images, but do keep those in a separate section in README.

**Comment by UppuluriKalyani** [comment]
@aviralgarg05 ok you have added twitter sentiment analysis and iris flower classification right...and please add readme file with clear description and  also results in that readme file then i will merge.

**Comment by aviralgarg05** [comment]
Ok I will make all the changes

**Review by UppuluriKalyani — APPROVED** [review]

**Pull request merged**
