### PR TITLE
Market Regime Detection

### PR DESCRIPTION
**Pull request by alo7lika**
#126 
The Market Regime Detection Project focuses on identifying distinct market conditions by analyzing historical stock price data using advanced data analysis techniques. By leveraging clustering algorithms, such as K-Means, the project classifies market regimes such as bull, bear, and neutral phases. This classification process involves several key components, including data collection from Yahoo Finance, preprocessing to calculate daily returns and volatility, and feature engineering to normalize the data for effective clustering. The project aims to provide traders and investors with valuable insights into market behavior, enhancing decision-making and risk management strategies. Through model validation and visualization of the identified regimes, the project illustrates the significance of time series analysis in financial markets, offering a robust tool for improved trading strategies.

### CODE REVIEW

**Comment by Neilblaze** [comment]
@alo7lika Contents are conflicting, squash and rebase the PR while making sure that the PR should **only** contain contents related to #126.

**Comment by alo7lika** [comment]
> Contents are conflicting, squash and rebase the PR while making sure that the PR should **only** contain contents related to #126.

Since I'm a beginner I don't have much knowledge but will try to keep those in mind. So what should I do now?

**Comment by Neilblaze** [comment]
Two ways, either do what I suggested, [squash and rebase](https://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) the current PR and keep the contents that are valid for the linked issue (#126), or, from your forked repo checkout a new branch and pull the changes (required for #123) into that branch & create a new PR. Once that's done, don't forget to link the issue and close this (#130) one.

**Review by UppuluriKalyani — APPROVED** [review]

**Comment by UppuluriKalyani** [comment]
@alo7lika okay I'm going add level3 for all 3 projects from next time onwards don't combine all of them just make separate PR for individual issues.

**Comment by alo7lika** [comment]
> @alo7lika okay I'm going add level3 for all 3 projects from next time onwards don't combine all of them just make separate PR for individual issues.

okay.Thank you @UppuluriKalyani

**Review by RadhikaMalpani1702 — COMMENTED** [review]
@MastanSayyad review this PR

**Review by MastanSayyad — COMMENTED** [review]
@UppuluriKalyani reduce it to level 2

**Comment by UppuluriKalyani** [comment]
> @UppuluriKalyani reduce it to level 2

She actually combined 3 issues implementations in 1 PR so combinely I gave level3.

**Comment by MastanSayyad** [comment]
okay that's understandable but you know right project additions are level 1 so make sure you don't give higher labels if it is not worth it, these project anyone can copy paste from the github ML repos and paste it here

**Comment by UppuluriKalyani** [comment]
> okay that's understandable but you know right project additions are level 1 so make sure you don't give higher labels if it is not worth it, these project anyone can copy paste from the github ML repos and paste it here

Yeah sure

**Pull request merged**
