### PR TITLE
AI-Powered Resume Analyzer with LLM #399

### PR DESCRIPTION
**Pull request by Niraj1608**
# Related Issues or bug
**Resume AI Analyzer project!** This project aims to leverage machine learning techniques to help job seekers optimize their resumes for specific job applications. We are excited to have contributors who are interested in improving the job application process through AI.

Fixes: #399 

# Proposed Changes
## Features

- **AI-Powered Resume Analysis**: Uses OpenAI and Gemini AI to analyze the content of resumes.
- **Keyword Extraction**: Extracts key information such as skills, experiences, and educational background.
- **Strengths and Weaknesses Identification**: Provides a detailed analysis of the candidate's strengths and areas of improvement.
- **Job Role Suggestions**: Suggests relevant job roles based on resume content to enhance the candidate's job search.
- **Resume Summarization**: Condenses the resume into a concise summary for quick evaluation.

### CODE REVIEW

**Comment by Niraj1608** [comment]
@UppuluriKalyani kindly review my pr :)

**Comment by UppuluriKalyani** [comment]
@Niraj1608 show me results (screenshots of screen recording)

**Comment by Niraj1608** [comment]
@UppuluriKalyani hey check
[AI_Powered_Resume_Analyzer.ipynb - Colab.pdf](https://github.com/user-attachments/files/17415786/AI_Powered_Resume_Analyzer.ipynb.-.Colab.pdf)

**Review by UppuluriKalyani — APPROVED** [review]

**Comment by Niraj1608** [comment]
@UppuluriKalyani Thank you :)

**Pull request merged**
