### PR TITLE
Created a text-to-music generator app on streamlit

### PR DESCRIPTION
**Pull request by Vishisht16**
Fixes: #29 

# Proposed Changes
 - A file that makes use of a model by Meta to create music and hosts it locally through streamlit

### CODE REVIEW

**Comment by SaiNivedh26** [comment]
Looks good ! Thank you for the contribution @Vishisht16

**Comment by Vishisht16** [comment]
@SaiNivedh26 level label please

**Comment by Vishisht16** [comment]
@SaiNivedh26 this was a level3 issue

**Comment by SaiNivedh26** [comment]
@Vishisht16 Level of this implementation only comes under level 1. The issue level also relabeles as well

**Pull request merged**
