### PR TITLE
Add Music Accompaniment Generator Project to ML-Nexus

### PR DESCRIPTION
**Pull request by NanFangDieDao**
Melodic accompaniment is an indispensable part of the music creation process. Traditionally, it has a high professional threshold. This undoubtedly poses a limitation to people lacking deep background knowledge of music who are motivated to undertake this activity for a variety of reasons, such as interest. A solution is needed to simplify the task of melodic accompaniment and enable non-specialists to participate in simple melodic accompaniment activities. At the same time, 
Transformer, which has emerged in the field of deep learning in recent years, has demonstrated high performance and great potential in various fields, and therefore, the use of deep learning techniques based on the Transformer model to simplify the task of melodic accompaniment is of great research value and possible to realize. 

   I use Python and Pytorch framework to design and implement the Transformer-based melody automatic accompaniment model. 

   In this project,I implement the innovative rule-based melody recognition algorithm and rule-based alignment algorithm to preprocess the dataset.After that I construct the Transformer model, including the embedding layer, the positional embedding layer, the self-attention layer, and encoder,decoder structures. The model can accept a MIDI file of the main melody and generate a corresponding MIDI file including main melody track together with other accompaniment instrument tracks such as piano,guitar,bass and drum.The project also provides the training, evaluation and validation results of the model.

### CODE REVIEW

**Comment by UppuluriKalyani** [comment]
Where did you raised an issue?...it's not the place to to raise an issue it's the place to make PR's for raised and assigned issues.

**Comment by NanFangDieDao** [comment]
> Where did you raised an issue?...it's not the place to to raise an issue it's the place to make PR's for raised and assigned issues. https://github.com/UppuluriKalyani/ML-Nexus/issues please raise there if you have any ideas and this project is already assigned to someone.

I have raise the issue in https://github.com/UppuluriKalyani/ML-Nexus/issues issue #122 , and here is my solution to the issue.

**Comment by UppuluriKalyani** [comment]
@NanFangDieDao can you please add readme file with clear description and with attached results..and also show here code works(results) it could be screen recording or screen shots...but I would prefer screen recording 
After review I will merge if it is good.

**Comment by NanFangDieDao** [comment]
> @NanFangDieDao can you please add readme file with clear description and with attached results..and also show here code works(results) it could be screen recording or screen shots...but I would prefer screen recording After review I will merge if it is good.

I've just added a README document to my project, and I believe I've described my project and its results in sufficient detail within it. @UppuluriKalyani

**Review by UppuluriKalyani — APPROVED** [review]

**Pull request merged**
